name: create_release_pull_request
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Which version are we creating a release pull request for?'
        required: true
      based_on_branch:
        description: 'Which branch should we base the release pull request on?'
        required: true
        default: master

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.event.inputs.based_on_branch }}"

      - name: Set up Go 1.17
        uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - name: validate version
        run: |
          echo "${{ github.event.inputs.release_version }}" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]'
          echo "${{ github.event.inputs.based_on_branch }}" | grep -E '^(master|release-[0-9]+\.[0-9]+)$'

      - run: make release-manifest promote-staging-manifest
        env:
          NEWVERSION: "${{ github.event.inputs.release_version }}"

      - name: Create release pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: Prepare ${{ github.event.inputs.release_version }} release"
          title: "chore: Prepare ${{ github.event.inputs.release_version }} release"
          branch: "release-${{ github.event.inputs.release_version }}"
          base: ${{ github.event.inputs.based_on_branch }}
